### ISSUE TITLE
Allow disabling black overlay for hero background

### ISSUE THREAD

**Issue by paulschaffrath** [theNewDynamic/gohugo-theme-ananke#235]

**Comment by remmelt** [comment]
I added some custom CSS to this effect:
```css
.cover .bg-black-60 {
    background-color: rgba(0,0,0,0);
}
```

**Comment by danielcorin** [comment]
I believe this can also be done by supplying an alternate class in the config file:
```toml
[[params]]
  cover_dimming_class = "<css_class_name>"
```
