### ISSUE TITLE
Share post via whatsapp

### ISSUE THREAD

**Issue by prdm0** [theNewDynamic/gohugo-theme-ananke#295]
I don't know how it works in other parts of the world, but here in Brazil many subjects are shared via Whatsapp. It would be interesting to also allow this form of sharing for posts.

**Comment by budparr** [comment]
We'll add this as a feature request. If you are technical, PRs are welcome as well. I don't know much about whatsapp, but the relevant partials are here: 

https://github.com/budparr/gohugo-theme-ananke/blob/master/layouts/partials/social-share.html
https://github.com/budparr/gohugo-theme-ananke/blob/master/layouts/partials/social-follow.html

**Comment by prdm0** [comment]
I tested the code below that I did and it worked. I just need to create a beautiful SVG file.

```
     {{ $whatsapp_href := printf "https://api.whatsapp.com/send?text=%s" $title}}
    <a href="{{ $whatsapp_href }}" class="whatsapp no-underline" aria-label="share on Whatsapp">
      {{ partialCached "svg/youtube.svg" (dict "size" $icon_size) $icon_size }}
    </a>
```

**Comment by prdm0** [comment]
Is it the SVG file that is sensitive to mouse placement?

**Comment by melvinsalas** [comment]
I'm not an expert on svg, but i draw this:

``` XML
<svg{{ with .size }} height="{{ . }}" {{ end }} style="enable-background:new 0 0 67 67;" version="1.1" viewBox="0 0 67 67" width="{{ .size }}" xml:space="preserve" 
    xmlns="http://www.w3.org/2000/svg" 
    xmlns:xlink="http://www.w3.org/1999/xlink">
    <path d="M30,60A30.008,30.008,0,0,1,18.323,2.357,29.812,29.812,0,0,1,30,0c.3,0,.608,0,.908.013.161,0,.338.012.54.021A29.911,29.911,0,0,1,51.2,8.778l.01.009.008.009.009.009c.037.036.073.073.109.11l.019.018.009.01.024.024.012.012a29.9,29.9,0,0,1,8.523,18.9c.005.074.01.147.014.221.009.134.017.277.025.449.009.2.016.379.021.54.009.3.014.606.014.908A29.976,29.976,0,0,1,30,60Zm-.01-48.276A17.85,17.85,0,0,0,14.531,38.48L12,47.724l9.458-2.48a17.844,17.844,0,1,0,8.532-33.52ZM29.984,44.4A14.983,14.983,0,0,1,21.9,42.014l-5.612,1.472,1.5-5.472a17.811,17.811,0,0,1-1.926-3.954,14.162,14.162,0,0,1-.693-4.5A14.828,14.828,0,1,1,29.984,44.4ZM23.673,21.325a1.621,1.621,0,0,0-1.188.558l-.09.1A4.916,4.916,0,0,0,20.925,25.6a8.5,8.5,0,0,0,1.815,4.6l0,.006c.015.02.042.058.08.113a19.291,19.291,0,0,0,7.534,6.617,26.058,26.058,0,0,0,2.541.94,5.72,5.72,0,0,0,1.727.262,7.3,7.3,0,0,0,1.081-.085c.816-.121,2.624-1.04,3.009-2.119a3.706,3.706,0,0,0,.26-2.12,1.423,1.423,0,0,0-.606-.4c-.078-.038-.16-.078-.249-.122-.44-.221-2.638-1.3-3.046-1.45a1.481,1.481,0,0,0-.479-.115.616.616,0,0,0-.525.339c-.311.466-1.207,1.513-1.412,1.748a.616.616,0,0,1-.48.254,1.108,1.108,0,0,1-.486-.144c-.073-.037-.172-.079-.3-.133a11.564,11.564,0,0,1-3.289-2.079,13.505,13.505,0,0,1-2.479-3.089c-.263-.45-.02-.694.194-.909.133-.132.288-.321.438-.5.077-.094.156-.19.232-.278a2.44,2.44,0,0,0,.385-.611l.065-.131a.822.822,0,0,0-.038-.782c-.077-.151-.516-1.222-.9-2.167-.182-.443-.352-.858-.47-1.141-.294-.705-.589-.764-.866-.764h-.137Z" style="fill-rule:evenodd;clip-rule:evenodd;" transform="translate(1.5,4)" />
</svg>
```

**Comment by prdm0** [comment]
@melvinsalas and @budparr, I did it but SVG doesn't have the effect when I put the mouse on top, just like with twitter and facebook icons. See [here](https://prdm0.rbind.io/post/workshop-paraibano-de-estat%C3%ADstica-2020/).

The good news is that my code works to share a post via whatsapp.

**Comment by prdm0** [comment]
I saw that the animation when placing the mouse on top is not made by the SVG file, there must be some HTML or CSS configuring this. I will search.

**Comment by melvinsalas** [comment]
Did you add the `.whatsapp` class into _social-icons.css?

<img width="513" alt="CleanShot 2020-06-15 at 16 22 57@2x" src="https://user-images.githubusercontent.com/708747/84711888-90213400-af24-11ea-9acc-88131812907e.png">

First, add `.whatsapp` into the first line to change color from black to gray.

Then, add the `:hover`, something like this:

``` CSS
.whatsapp:hover {
  fill: #128C7E;
}
```

Good luck!

**Comment by prdm0** [comment]
It remains black. My file is:

```css
.facebook, .twitter, .instagram, .youtube, .github, .gitlab, .keybase, .linkedin, .medium, .mastodon, .slack, .stackoverflow, .rss, .whatsapp {
  fill: #BABABA;
}

.new-window {
  opacity: 0;
  display: inline-block;
  vertical-align: top;
}
.link-transition:hover .new-window{
  opacity: 1;
}

.facebook:hover {
  fill: #3b5998;
}

.twitter:hover {
  fill: #1da1f2;
}

.instagram:hover {
  fill: #e1306c;
}

.youtube:hover {
  fill: #cd201f;
}

.github:hover {
  fill: #6cc644;
}

.gitlab:hover {
  fill: #FC6D26;
}

.keybase:hover {
  fill: #3d76ff;
}

.linkedin:hover {
  fill: #0077b5
}

.medium:hover {
  fill: #0077b5
}

.mastodon:hover {
  fill: #3088d4;
}

.slack:hover {
  fill: #E01E5A;
}

.stackoverflow:hover {
  fill: #f48024;
}

.rss:hover{
  fill: #ff6f1a;
}

.whatsapp:hover {
  fill: #128C7E;
}
```

I think the SVG should be transparent.
