### ISSUE TITLE
Move footer to bottom and make main full height with flexbox

### ISSUE THREAD

**Issue by DanielRuf** [theNewDynamic/gohugo-theme-ananke#370]
The pb7 trick is not that ideal. You can move the footer to the bottom with the following:

```css
html, body {
    height: 100%;
}

body {
    display: flex;
    flex-direction: column;
}

main {
    flex: 1 0 auto;
}

footer {
    flex-shrink: 0;
}
```

See also https://css-tricks.com/couple-takes-sticky-footer/
