### ISSUE TITLE
Improve Social API

### ISSUE THREAD

**Issue by regisphilibert** [theNewDynamic/gohugo-theme-ananke#422]
Users need to be able to customize/add social service with icons. We'll cater for some built in and direct users how to add new ones. 
The new UX will handle better ordering, more customization, easy addition of future customization.

We'll make this retrocompatible.
#### UX

Old UX:
```yaml
# config/_default/params.yaml
description: Something lorem ipsum
twitter: https://twitter.com/GoHugoIO
github: https://github.com/GoHugoIO

```
New UX:

```yaml
# config/_default/params.yaml
ananke_socials:
- name: twitter
   url: https://twitter.com/GoHugoIO
   color: #1da1f2
- name: github
   url: https://github.com/GoHugoIO
   color: #6cc644
```

#### Adding user's own icon

User will be directed to add an svg file matching the service's name at `/assets/ananke/icons/`

Ex: If user wants to add twitch:
```
ananke_socials:
- name: twitch
   url: https://twitch.com/GoHugoIO
```
User will drop its svg as `/assets/ananke/icons/twitch.svg`

#### Adding built in icons/service

This will also improve the way contributor can submit new built in services by complementing a single source file for service name and color and add one (consistent formating) svg.

This should take care or help contributors handling #420 #419 #418 and more...
