### ISSUE TITLE
Layout suggestions for tags and related content

### ISSUE THREAD

**Issue by chuxinyuan** [theNewDynamic/gohugo-theme-ananke#433]
# about tags

Tags are usually no more than 5, so it is better to arrange them horizontally on both mobile phones and computers

# about related content

I've adjusted it down here with custom_css

```css
code {
  padding: 2px 4px;
  border-radius: 4px
}

.cf {
  text-align: justify;
  opacity: 1.0;
  width: 100%;
  height: auto;
}

.nested-links {
  text-align: justify;
  opacity: 1.0;
  width: 100%;
  height: auto;
}

div {
  opacity: 1.0;
}
```

But the width of the relevant content box is too narrow, how to adjust to the same width as the code box?

![](https://rbind.gitee.io/img/20210821113754.png)
