### ISSUE TITLE
Main menu links are incorrect under certain circumstances

### ISSUE THREAD

**Issue by tamaracha** [theNewDynamic/gohugo-theme-ananke#604]
Hi, I have a situation where links in the main navigation coming from config are not correct:

- multilingual setup with defaultContentLanguageInSubdir
- baseURL has a subdirectory
- Most menu items come from frontmatter
- A few menu items come from menus.main in config
- hugo v0.109.0

For frontmatter menu items, your site_navigation template generates the correct links, because .URL is already the .RelPermalink. The URLs from manual config items are missing the language prefix and need a relLangURL or absLangURL pipe which prepends it.

**Comment by jmooring** [comment]
This can be closed.

I suspect the OP was setting the `url` parameter in site config menu entries instead of setting `pageRef`. See <https://gohugo.io/content-management/menus/#define-in-site-configuration>.

Here's a properly configured multilingual single-host site:

<details>
<summary>hugo.toml</summary>

```toml
baseURL = 'https://example.org/foo/'
title = 'My New Hugo Site'
theme = 'ananke'

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

# -----------------------------------------------------------------------------
# Languages
# -----------------------------------------------------------------------------

[languages.en]
languageCode = 'en-US'
languageDirection = 'ltr'
languageName = 'English'
weight = 1

[languages.de]
languageCode = 'de-DE'
languageDirection = 'ltr'
languageName = 'Deutsch'
weight = 2

# -----------------------------------------------------------------------------
# Menus
# -----------------------------------------------------------------------------

# English

[[languages.en.menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[languages.en.menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

# Deutsch

[[languages.de.menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[languages.de.menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

```
</details>
<br>

Works great with or without a subdirectory in the `baseURL`.
