### ISSUE TITLE
i18n problem

### ISSUE THREAD

**Issue by Pathsis** [theNewDynamic/gohugo-theme-ananke#611]
After switching the site language, the header information shows that the site language is still the main language.

<img width="1800" alt="截屏2023-01-29 21 55 48" src="https://user-images.githubusercontent.com/72077265/215330971-07248f86-b8c7-4b86-b7c9-1628621f3bb8.png">

**Comment by regisphilibert** [comment]
Yes we're using `site.LanguageCode` here which is expecting the language to hold a `languageCode` key. Not sure how your language settings are set but from a regular config file you should have:

```
languages:
  en: 
    name: English
    languageCode: en
  fr:
    name: Français
    languageCode: fr-fr
```

I opened a [ticket](https://github.com/gohugoio/hugo/issues/10690) so that `site.LanguageCode` defaults on the language key when `languageCode` is not set for a given language.
