### ISSUE TITLE
Show categories

### ISSUE THREAD

**Issue by danger89** [theNewDynamic/gohugo-theme-ananke#620]
You only list the tags of the Hugo posts. But Hugo also supports [`categories` as taxonomies](https://gohugo.io/content-management/taxonomies/#example-front-matter-with-taxonomies). Could you please also show them when viewing the post?

Example of the markdown page section with `categories`:

```yaml
categories:
  - Beginner
  - Server
tags:
  - cicd
  - docker
  - free
```
