### ISSUE TITLE
Images not rendered in alternative language

### ISSUE THREAD

**Issue by yonz2** [theNewDynamic/gohugo-theme-ananke#666]
Hi,

I defined two languages in my hugo.yaml file English (Default) and German
```
theme: 
  - github.com/theNewDynamic/gohugo-theme-ananke
languageCode: 'en-us'
DefaultContentLanguage: en 
languages:
  en:
    title: 'My Company'
    weight: 1
    languageName: English
  de:
    title: 'Meine Firma'
    weight: 2
    languageName: Deutsch
```
I have two markdown files ("offering.md", and "offering.de.md"), both have the following content:
```
...
![Placeholder for Offerings Image](images/Offerings_16x9.png)

## Our Offerings
...

```
The placeholder is, in both language versions, rendered as:
```
<img src="images/Offerings_16x9.png" alt="Placeholder for Offerings Image">
```
however the base URL for the German has an `de` at the end, so when I switch to German, the browser is looking for the image at `http://127.0.0.1:1313/de/images/Offerings_16x9.png` and of course not finding it. As it is actually located at  `http://127.0.0.1:1313/images/Offerings_16x9.png` 

How can I fix that?

Any help will be much appreciated
Yonz

p.s.
I'm running this on Github CodeSpace:
```
@yonz2 ➜ /workspaces/myproject (main) $ hugo version
hugo v0.120.4-f11bca5fec2ebb3a02727fb2a5cfb08da96fd9df linux/amd64 BuildDate=2023-11-08T11:18:07Z VendorInfo=gohugoio
```
