### ISSUE TITLE
Error when trying to build on Netlify

### ISSUE THREAD

**Issue by frabac72** [theNewDynamic/gohugo-theme-ananke#704]
Error: "/opt/build/repo/themes/ananke/layouts/robots.txt:3:1": parse failed: template: robots.txt:3: illegal number syntax: "-"
Googling around it would seem the two spaces before the final "dash" are what messes up the whole thing. Can one of two spaces near the end of line 3 be removed, please?

**Comment by davidsneighbour** [comment]
Hi @frabac72, it looks like I can't reproduce your issue. How does your netlify.toml look like? I think you might have to define a `HUGO_ENV` containing "production" in there somewhere.

My own netlify.toml has this part:

```toml
[context.production.environment]
HUGO_VERSION = "0.133.1"
HUGO_ENV = "production"
```
